name: mt-cnn
channels:
  - defaults
  - conda-forge
dependencies:
  - astropy=4.0.2
  - dataclasses=0.8
  - gensim=3.8.3
  - keras-gpu=2.3.1
  - matplotlib=3.3.4
  - nltk=3.5
  - numba=0.53.1
  - numpy=1.19.2
  - pandas=1.1.3
  - patsy=0.5.1
  - pymc3=3.8
  - python=3.6.13
  - requests=2.25.1
  - scikit-learn=0.24.1
  - smart_open=5.0.0
  - tensorflow=1.15.0
  - torchvision=0.4.2
  - tqdm=4.59.0
  - transformers=4.4.2
